### ISSUE TITLE
Installed app doesn't appear in grafana menu

### ISSUE THREAD

**Issue by antgit** [grafana/example-app#5]
I installed grafana 4.2.0 for windows and copied content of "dist" folder into data/plugins folder. After this I restarted grafana server and enabled this plugin in setting. But somehow it still doesn't appear in grafana menu.

**Comment by daniellee** [comment]
That is a setting in the plugin.json. See the [WorldPing App](https://github.com/raintank/worldping-app/blob/master/dist/plugin.json#L95-L102) for an example.
